spring:
  application:
    name: CONFIG-DEFAULT

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
